baseurl: "" # the subpath of your site, e.g. /blog
url:     "https://sebreategui.com"
locale:  "en-AU"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
- Rakefile


sass:
  style: compressed
  load_paths:
    # Use a managed version of Bootstrap
    'vendor/bootstrap-4.3.1/assets/stylesheets/'

# Metadata for <head>
title:        Sebastian Reategui
titleLong:    Sebastian Reategui, photographer
description:  |
  A photographer and videographer from Sydney, Australia. View photojournalism, design concepts, and video work.
thumbnail:
  url:    "/img/sebastian-reategui-site-thumb.jpg"
  width:  1280
  height: 853

# Author info
author:
  name:  Sebastian Reategui
  email: seb.reategui@gmail.com
  url: https://sebreategui.com
  photo:
    url:    "/img/profiles/profile-square-sebastian-reategui-by-david-puentes.jpg"
    width:  300
    height: 300
  social_media:
    twitter:
      network:  Twitter
      handle:   "@spebz"
      url:      https://twitter.com/spebz
    instagram:
      network:  Instagram
      handle:   "@seb_rg"
      url:      https://instagram.com/seb_rg
    facebook:
      network:  Facebook
      handle:   "@seb.reategui"
      url:      https://facebook.com/seb.reategui
    youtube:
      network:  YouTube
      handle:   "@sebreategui"
      url:      https://youtube.com/sebreategui
    vimeo:
      network:  Vimeo
      handle:   "@sebreategui"
      url:      https://vimeo.com/sebreategui
    tumblr:
      network:  Tumblr
      handle:   "spebz"
      url:      https://spebz.tumblr.com
    linkedin:
      network:  LinkedIn
      handle:   Sebastian Reategui
      url:      https://linkedin.com/in/sebastianreategui
    github:
      network:  GitHub
      handle:   seb26
      url:      https://github.com/seb26/

# Permalink for blog posts
permalink: /post/:year/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      schemaType: 'WebSite'
      schemaTypeOG: 'website'
      gallery_footer: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: blog
      classes: 'nav-static'
      author: default
      schemaType: 'BlogPosting'
      schemaTypeOG: 'article'
      thumbnail:
        width: "1280"
        height: "853"
        format: jpg
      gallery_dimensions:
        width: "1280"
        height: "853"
      gallery_footer: true
