# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seb26.github.io"

# Metadata for <head>
title: Sebastian Reategui
titleLong: Sebastian Reategui, photographer
locale: "en_AU"
description: |
  A photographer and videographer from Sydney, Australia. View photojournalism, design concepts, and video work.
thumbnail:
  url: "/img/sebastian-reategui-site-thumb.jpg"
  width: 500px
  height: 500px

# Author info
author:
  name: Sebastian Reategui
  email: seb.reategui@gmail.com
  social_media:
    twitter:
      network: Twitter
      handle: "@sebreategui"
      url: https://twitter.com/sebreategui
    instagram:
      network: Instagram
      handle: "@seb_rg"
      url: https://instagram.com/seb_rg
    facebook:
      network: Facebook
      handle: "@seb.reategui"
      url: https://facebook.com/seb.reategui
    youtube:
      network: YouTube
      handle: "@sebreategui"
      url: https://youtube.com/sebreategui
    vimeo:
      network: Vimeo
      handle: "@sebreategui"
      url: https://vimeo.com/sebreategui
    tumblr:
      network: Tumblr
      handle: "spebz"
      url: https://spebz.tumblr.com
    linkedin:
      network: LinkedIn
      handle: Sebastian Reategui
      url: https://linkedin.com/in/sebastianreategui
    github:
      network: GitHub
      handle: seb26
      url: https://github.com/seb26/

# Collections, for recent work
collections:
  recent:
    output: true
    layout: recent


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed
